{
 "title": "Dashboard Procesador",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "OS", "query": "RaspbianOS" }
  ]
 },
 "panels": [
  {
   "title": "Procesador ${OS}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"model\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura Promedio ${OS}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avgTemp\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, TempRaspbian: r.avgTemp}))\n  |> mean(column: \"TempRaspbian\")\n  "
    }
   ]
  },
  {
   "title": "Uso Promedio ${OS}",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"overallUsage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, UsageRaspbian: r.overallUsage}))\n  |> mean(column: \"UsageRaspbian\")\n  "
    }
   ]
  },
  {
   "title": "Temperatura Promedio ${OS}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avgTemp\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, TempRaspbian: r.avgTemp}))"
    }
   ]
  },
  {
   "title": "Uso de Procesador Promedio ${OS}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"overallUsage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, UsageRaspbian: r.overallUsage}))"
    }
   ]
  },
  {
   "title": "Temperatura Promedio Actual ${OS}",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avgTemp\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, TempRaspbian: r.avgTemp}))\n  |> last(column: \"TempRaspbian\")"
    }
   ]
  },
  {
   "title": "Uso de Procesador Promedio Actual ${OS}",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"overallUsage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, UsageRaspbian: r.overallUsage}))\n  |> last(column: \"UsageRaspbian\")"
    }
   ]
  },
  {
   "title": "Temperatura Máxima ${OS}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"maxTemp\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, TempRaspbian: r.maxTemp}))"
    }
   ]
  },
  {
   "title": "Uso de Procesador Promedio ${OS}",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_1_usage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core1: r.core_1_usage}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MacOS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_2_usage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core2: r.core_2_usage}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MacOS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_3_usage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core3: r.core_3_usage}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MacOS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_4_usage\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core4: r.core_4_usage}))"
    }
   ]
  },
  {
   "title": "Velocidad por Core ${OS}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mhz" } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_1_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core1: r.core_1_speed}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_2_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core2: r.core_2_speed}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_3_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core3: r.core_3_speed}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_4_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core4: r.core_4_speed}))"
    }
   ]
  },
  {
   "title": "Velocidad por Core ${OS}",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_1_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core1: r.core_1_speed}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_2_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core2: r.core_2_speed}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_3_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core3: r.core_3_speed}))"
    },
    {
     "query": "from(bucket: \"testBucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${OS}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"core_4_speed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, Core4: r.core_4_speed}))"
    }
   ]
  }
 ]
}